In [2]:
from transformers import pipeline
classifier = pipeline('sentiment-analysis')

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
D:\маг1курс\ІАД\lab4\.venv\Lib\site-packages\huggingface_hub\file_download.py:140: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\111\.cache\huggingface\hub\models--distilbert--distilbert-base-uncased-finetuned-sst-2-english. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode

All PyTorch model weights were used when initializing TFDistilBertForSequenceClassification.

All the weights of TFDistilBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.
Device set to use 0


In [5]:
# Класифікація тексту по сенсовому забарвленню (positive or negative)
txt_1 = 'Football is the most exciting and popular game in the world'
classifier(txt_1)

[{'label': 'POSITIVE', 'score': 0.9998573064804077}]

In [4]:
txt_2 = 'I am very disappointed with the results.'
classifier(txt_2)

[{'label': 'NEGATIVE', 'score': 0.9997926354408264}]

In [6]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
model_name = "distilbert-base-uncased-finetuned-sst-2-english"
model = TFAutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

D:\маг1курс\ІАД\lab4\.venv\Lib\site-packages\huggingface_hub\file_download.py:140: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\111\.cache\huggingface\hub\models--distilbert-base-uncased-finetuned-sst-2-english. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
All PyTorch model weights were used when initializing TFDistilBertForSequenceClassification.

All

In [8]:
# Дефолтна токенізація
inputs = tokenizer([txt_1, txt_2])
inputs

{'input_ids': [[101, 2374, 2003, 1996, 2087, 10990, 1998, 2759, 2208, 1999, 1996, 2088, 102], [101, 1045, 2572, 2200, 9364, 2007, 1996, 3463, 1012, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

In [10]:
# Токенізація з параметрами
inputs_with_padding = tokenizer([txt_1, txt_2], padding = True, truncation = True, max_length = 256, return_tensors="tf")
inputs_with_padding

{'input_ids': <tf.Tensor: shape=(2, 13), dtype=int32, numpy=
array([[  101,  2374,  2003,  1996,  2087, 10990,  1998,  2759,  2208,
         1999,  1996,  2088,   102],
       [  101,  1045,  2572,  2200,  9364,  2007,  1996,  3463,  1012,
          102,     0,     0,     0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 13), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]], dtype=int32)>}

In [13]:
# Пропускання токенізованого тексту через модель
outputs = model(inputs_with_padding)
outputs

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-4.24948  ,  4.605344 ],
       [ 4.707576 , -3.7732737]], dtype=float32)>, hidden_states=None, attentions=None)

In [12]:
# Ймовірності забарвлення тексту (стовпці 0 - negative, 1 - positive)
import tensorflow as tf
predictions = tf.nn.softmax(outputs[0], axis=-1)
predictions

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.4267136e-04, 9.9985731e-01],
       [9.9979264e-01, 2.0735948e-04]], dtype=float32)>

In [39]:
# Україномовна модель для визначення в тексті слів, що означають локацію, людину або організацію
from transformers import TFAutoModelForTokenClassification

model_name = "ukr-models/uk-ner" 
model = TFAutoModelForTokenClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)


Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFXLMRobertaForTokenClassification: ['roberta.embeddings.position_ids']
- This IS expected if you are initializing TFXLMRobertaForTokenClassification from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFXLMRobertaForTokenClassification from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFXLMRobertaForTokenClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFXLMRobertaForTokenClassification for predictions without further training.


In [40]:
import tensorflow as tf
import tokenize_uk

def get_word_predictions(model, tokenizer, texts):
    results = []

    for text in texts:
        tokens = tokenize_uk.tokenize_text(text)
        inputs = tokenizer(text, return_tensors="tf", padding=True, truncation=True)
        
        outputs = model(**inputs)
        logits = outputs.logits  
        predictions = tf.argmax(logits, axis=-1)  

        word_predictions = []
        tokens_index = 0 

        for i, token in enumerate(inputs['input_ids'][0]):
            if token != tokenizer.pad_token_id: 
                label_id = predictions[0][tokens_index].numpy()  
                label = model.config.id2label[label_id]  
                word_predictions.append({"word": tokenizer.decode([token]), "label": label})
                tokens_index += 1

        results.append(word_predictions)

    return results

In [54]:
def visualize_predictions(predictions):
    label_dict = {
        'B-PER': 'Person',
        'I-PER': 'Person',
        'B-LOC': 'Location',
        'I-LOC': 'Location',
        'B-ORG': 'Organization',
        'I-ORG': 'Organization',
        'O': 'Other'
    }
    
    print(f"{'Word':<15}{'Label'}")
    print("-" * 30)  

    for sentence in predictions:
        for token_info in sentence:
            word = token_info['word']
            label = token_info['label']
            if label != 'O':
                label_value = label_dict.get(label, label)  
                print(f"{word:<15}{label_value}")

In [55]:
# Тестування на прикладі
texts = ["Микола Лисенко був видатним українським композитором. Він народився в Києві, але частину свого життя провів у Львові. У Києві він заснував музичну школу, а також працював в оперному театрі. Лисенко співпрацював з багатьма художніми колективами, серед яких був Національний ансамбль пісні та танцю України."]
predictions = get_word_predictions(model, tokenizer, texts)
print(predictions)

[[{'word': '<s>', 'label': 'O'}, {'word': 'Микола', 'label': 'B-PER'}, {'word': 'Лис', 'label': 'I-PER'}, {'word': 'енко', 'label': 'I-PER'}, {'word': 'був', 'label': 'O'}, {'word': 'видат', 'label': 'O'}, {'word': 'ним', 'label': 'O'}, {'word': 'українським', 'label': 'O'}, {'word': 'композитор', 'label': 'O'}, {'word': 'ом', 'label': 'O'}, {'word': '.', 'label': 'O'}, {'word': 'Він', 'label': 'O'}, {'word': 'народився', 'label': 'O'}, {'word': 'в', 'label': 'O'}, {'word': 'Києві', 'label': 'B-LOC'}, {'word': ',', 'label': 'O'}, {'word': 'але', 'label': 'O'}, {'word': 'частину', 'label': 'O'}, {'word': 'свого', 'label': 'O'}, {'word': 'життя', 'label': 'O'}, {'word': 'пров', 'label': 'O'}, {'word': 'ів', 'label': 'O'}, {'word': 'у', 'label': 'O'}, {'word': 'Львові', 'label': 'B-LOC'}, {'word': '.', 'label': 'O'}, {'word': 'У', 'label': 'O'}, {'word': 'Києві', 'label': 'B-LOC'}, {'word': 'він', 'label': 'O'}, {'word': 'зас', 'label': 'O'}, {'word': 'н', 'label': 'O'}, {'word': 'ував', 

In [56]:
# Видає лише визначені слова
visualize_predictions(predictions)

Word           Label
------------------------------
Микола         Person
Лис            Person
енко           Person
Києві          Location
Львові         Location
Києві          Location
Лис            Person
енко           Person
Національний   Organization
ансамбл        Organization
ь              Organization
пісні          Organization
та             Organization
танц           Organization
ю              Organization
України        Organization
